ui:
  title: Формирование данных

spring:
  application:
    name: GoodsBuilder
  jmx:
    enabled: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
          ddl-auto: create
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/embedded
    initialize: true
    username: sa
    password: