--Должно соответствовать DictionaryType
INSERT INTO PUBLIC.DICTIONARY(ID, NAME) SELECT * FROM (SELECT 1, 'CONTENT_NAME' UNION SELECT 2, 'FABRICATOR_NAME') DICTIONARY_TYPES WHERE NOT EXISTS(SELECT * FROM PUBLIC.DICTIONARY);
-- 
-- INSERT INTO PUBLIC.DICTIONARY_VALUE(ID, VALUE, ID_DICTIONARY) VALUES (1, 'TEST1', 1), (2, 'TEST2', 1), (3, 'TEST3', 2);
--
-- INSERT INTO PUBLIC.CONTENT(ID, AMOUNT, ID_NAME) VALUES (1, 23, 1);
-- INSERT INTO PUBLIC.FABRICATOR(ID, ID_NAME) VALUES (1, 1);
-- INSERT INTO PUBLIC.FABRICATOR_CONTENT(ID_FABRICATOR, ID_CONTENT) VALUES (1, 1);
-- INSERT INTO PUBLIC.PRODUCT(ID, DESCRIPTION, IMAGE_NAME, PRICE, WEIGHT) VALUES (1, 'SOME DESC', 'test.png', 20, 20);
-- INSERT INTO PRODUCT_FABRICATOR(ID_FABRICATOR, ID_PRODUCT) VALUES (1,1);